name: Publish Blog
on: [push, pull_request]
jobs:

  build:
    name: "Publish My Blog"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/kivinsae.key
          chmod 600 ~/.ssh/kivinsae.key
          chmod 700 ~/.ssh
          cat >>~/.ssh/config <<END
          Host kivinsae-blog
            HostName $SSH_HOST
            User $SSH_USER
            Port 22
            IdentityFile ~/.ssh/kivinsae.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.KIVINSAE_BLOG_USERNAME }}
          SSH_KEY: ${{ secrets.KIVINSAE_BLOG_RSAKEY }}
          SSH_HOST: ${{ secrets.KIVINSAE_BLOG_HOST }}

      - name: Make the public_sync script could be executed.
        run: ssh kivinsae-blog 'chmod +x /opt/hexo/public_sync.sh'

      - name: Executing remote ssh commands to republish blog
        run: ssh kivinsae-blog '/usr/local/bin/public_sync'