name: Publish Blog
on: [push, pull_request]
jobs:
  build:
    name: "Publish My Blog"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/kivinsae.key
          chmod 600 ~/.ssh/kivinsae.key
          chmod 700 ~/.ssh
          cat >>~/.ssh/config <<END
          Host kivinsae-blog
            HostName $SSH_HOST
            User $SSH_USER
            Port 22
            IdentityFile ~/.ssh/kivinsae.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.KIVINSAE_BLOG_USERNAME }}
          SSH_KEY: ${{ secrets.KIVINSAE_BLOG_RSAKEY }}
          SSH_HOST: ${{ secrets.KIVINSAE_BLOG_HOST }}

      - name: Clone the master branch of kivinsae-blog
        run: git clone git@github.com:KKtheGhost/kivinsae_blog.git --config core.sshCommand="ssh -i ~/.ssh/kivinsae.key"

      - name: Generate the config.yml from templates
        run: |
          cp -rf _config.module.yml _config.yml
          cp -rf node_modules/hexo-theme-landscape/_config.module.yml node_modules/hexo-theme-landscape/_config.yml
        working-directory: ./kivinsae_blog

      - name: Replace the SECRETS in config.yml
        run: |
          sed -i "s/TAG_ENCRYPT_PSWD/$ENCRYPT_PSWD/g" _config.yml
          sed -i "s/TAG_PRIVATE_PSWD/$PRIVATE_PSWD/g" _config.yml
          sed -i "s/LEANCLOUD_APPID/$LC_APPID/g" node_modules/hexo-theme-landscape/_config.yml
          sed -i "s/LEANCLOUD_APPKEY/$LC_APPKEY/g" node_modules/hexo-theme-landscape/_config.yml
        working-directory: ./kivinsae_blog
        env:
          ENCRYPT_PSWD: ${{ secrets.BLOG_ENCRYPT }}
          PRIVATE_PSWD: ${{ secrets.BLOG_PRIVATE }}
          LC_APPID: ${{ secrets.LEANCLOUD_APPID }}
          LC_APPKEY: ${{ secrets.LEANCLOUD_APPKEY }}

      - name: Install NPM and OSSUTIL
        run: |
          curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
          sudo apt-get install -y nodejs
          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
      
      - name: Generate the Blog content
        run: |
          npm install
          hexo clean
          hexo generate
        working-directory: ./kivinsae_blog

      - name: Configure OSS
        run: |
          touch ~/.ossutilconfig
          chmod 644 ~/.ossutilconfig
          cat >>~/.ossutilconfig <<END
          [Credentials]
          language=EN
          endpoint=oss-accelerate.aliyuncs.com
          accessKeyID=$OSSID
          accessKeySecret=$OSSSECRET
          END
        env:
          OSSID: ${{ secrets.ALIYUN_KEYID }}
          OSSSECRET: ${{ secrets.ALIYUN_KEYTOKEN }}

      - name: Upload artifacts to OSS
        run: ossutil64 sync ./kivinsae_blog/public/ oss://kivinsae-blog-web/ --delete --force

