name: Publish Blog
on: [push]
jobs:

  build:
    name: Publish My Blog
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.KIVINSAE_BLOG_HOST }}
        username: ${{ secrets.KIVINSAE_BLOG_USERNAME }}
        password: ${{ secrets.KIVINSAE_BLOG_PASSWORD }}
        port: 22
        script: /usr/local/bin/public_sync